<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Configuration_Management</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyTitle>1С Управление Конфигурациями</AssemblyTitle>
    <Product>1С Управление Конфигурациями</Product>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PublishReadyToRun>false</PublishReadyToRun>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

</Project>
